# https://github.com/GoogleCloudPlatform/functions-framework-python/blob/main/examples/docker-compose/Dockerfile

# Use the Python base image
FROM python

# Set a working directory
WORKDIR /agents-llm-calls

# Copy all the files from the local directory into the container
COPY ./backend/src/llm_calls/ .

# Install the Functions Framework
RUN pip install functions-framework

# Install any dependencies of the function
RUN pip install -r requirements.txt

# Run the function
CMD ["functions-framework", "--target=main", "--debug"]