# builds image for the agents front end
FROM node:latest

WORKDIR agents-app

COPY ./components ./components
COPY ./pages ./pages
COPY ./public ./public
COPY ./styles ./styles
COPY ./utils ./utils
COPY ./.next ./.next
COPY jsconfig.json jsconfig.json
COPY next.config.js next.config.js
COPY package-lock.json package-lock.json
COPY package.json package.json
COPY README.md README.md
COPY .env.local .env.local

RUN npm install

RUN npm run build

EXPOSE 1234

CMD ["npm", "run", "start"]
