# builds image for the agents backend
FROM python:3.10

WORKDIR /backend

# need cmake for scikit
RUN apt-get update && apt-get install -y python3-pip cmake netcat-openbsd wkhtmltopdf

COPY ./backend/requirements.txt ./requirements.txt

RUN pip install -r ./requirements.txt

# expose python server port
EXPOSE 1235

# create empty analysis assets dirs
RUN mkdir -p /agents-assets/analysis-assets
RUN mkdir -p /agents-assets/analysis-assets/boxplots 
RUN mkdir -p /agents-assets/analysis-assets/datasets 
RUN mkdir -p /agents-assets/analysis-assets/heatmaps 
RUN mkdir -p /agents-assets/analysis-assets/linechart 
RUN mkdir -p /agents-assets/analysis-assets/linecharts
RUN touch /agent-logs-out

ENV PYTHONUNBUFFERED=true

# Set the environment variables (avoid prompts during installations)
ENV ACCEPT_EULA=Y
ENV DEBIAN_FRONTEND=noninteractive

# Install utilities and prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
  gnupg \
  curl \
  ca-certificates \
  unixodbc-dev

# Add the Microsoft repository key and repository
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Install SQL Server ODBC Driver
RUN apt-get update && apt-get install -y --no-install-recommends \
  msodbcsql18

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# start startup script
CMD sh ./startup.sh