# get nginx
FROM nginx:latest

ARG DEFOG_API_KEY
ARG DEFOG_API_KEY_NAMES
ARG GOOGLE_CLIENT_ID
ARG BUTTON_TEXT
ARG ALLOW_UPDATES
ARG COPY_SSL_CERT

# copy the nginx config file
# change nginx_local.conf to nginx_prod.conf if running on a production server
# COPY ./nginx/nginx_prod.conf /etc/nginx/nginx.conf
COPY ./nginx/nginx_local.conf /etc/nginx/nginx.conf

# copy the build output to replace the default nginx contents
COPY ./frontend/out /var/www/html

# uncomment these lines if running in production
# COPY ./defogcert.pem /etc/ssl/certs/defogcert.pem
# COPY ./defogkey.pem /etc/ssl/private/defogkey.pem

# run nginx
CMD ["nginx", "-g", "daemon off;"]