FROM node:20.11.1

WORKDIR partykit-server

COPY ./backend/src/partykit-server ./

RUN npm install

RUN apt-get update && apt-get install -y nginx

# copy nginx config
COPY ./backend/docker-setup-files/nginx.conf /etc/nginx/sites-available/default

EXPOSE 1999
EXPOSE 2000

CMD service nginx start && npx partykit dev --disable-request-cf-fetch