# https://github.com/GoogleCloudPlatform/functions-framework-python/blob/main/examples/docker-compose/Dockerfile

# Use the Python base image
FROM python

# Set a working directory
WORKDIR /agents-llm-calls

COPY ./backend/llm_calls/requirements.txt ./requirements.txt

# Install any dependencies of the function
RUN pip install -r requirements.txt

# Install the Functions Framework
RUN pip install functions-framework


# Copy all the files from the local directory into the container
COPY ./backend/llm_calls/ .

# Run the function
CMD ["functions-framework", "--target=main", "--debug"]