FROM python:3.10

WORKDIR gcs-consumer

ARG GOOGLE_APPLICATION_CREDENTIALS_PATH

# copy rabbitmq installation script
COPY ./agents-backend/docker-setup-files/install_rabbitmq.sh /install_rabbitmq.sh

# install rabbitmq
RUN chmod +x /install_rabbitmq.sh
RUN /install_rabbitmq.sh

# remove rabbitmq installation script
RUN rm /install_rabbitmq.sh

# copy google creds
COPY $GOOGLE_APPLICATION_CREDENTIALS_PATH /cloud-storage-creds.json

EXPOSE 5672

EXPOSE 15672

# copy gcs_consumer python script
COPY ./agents-backend/agents/gcs_consumer.py ./gcs_consumer.py

RUN pip install google-cloud-storage pika colorama

# need an admin user to access via pika on other containers
CMD service rabbitmq-server start && \
    rabbitmq-plugins enable rabbitmq_management && \
    rabbitmqctl add_user admin admin && \
    rabbitmqctl set_user_tags admin administrator && \
    rabbitmqctl set_permissions -p / admin ".*" ".*" ".*" && \
    python3 gcs_consumer.py