# builds image for the agents backend
FROM python:3.12-slim

WORKDIR /backend

RUN apt-get update && apt-get install -y python3-pip

# Install uv
RUN pip install uv

COPY ./backend/requirements.txt /root/requirements.txt

# Use uv to install dependencies system-wide
RUN uv pip install --system --upgrade setuptools && \
    uv pip install --system -r /root/requirements.txt

# expose python server port
EXPOSE 1235

RUN touch /agent-logs-out

ENV PYTHONUNBUFFERED=true

# Set the environment variables (avoid prompts during installations)
ENV ACCEPT_EULA=Y
ENV DEBIAN_FRONTEND=noninteractive

# Install utilities and prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
  gnupg \
  curl \
  ca-certificates \
  unixodbc-dev

# Add the Microsoft repository key and repository
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Install SQL Server ODBC Driver
RUN apt-get update && apt-get install -y --no-install-recommends \
  msodbcsql18

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# run start_docker.sh file as entrypoint to run as PID 1
ENTRYPOINT ["/backend/startup.sh"]