# builds image for the agents backend
FROM python:3.10

WORKDIR agents-python-server

ARG OPENAI_API_KEY=""

# set env vars
ENV OPENAI_API_KEY=$OPENAI_API_KEY

# need cmake for scikit
RUN apt-get update && apt-get install -y python3-pip cmake supervisor cron

COPY ./agents-backend/agents/requirements.txt ./requirements.txt
# install requirements
RUN pip install -r requirements.txt

# copy deletion cron
COPY ./agents-backend/docker-setup-files/delete-cron /etc/cron.d/delete-cron

# copy startup script
COPY ./agents-backend/docker-setup-files/startup.sh /startup.sh

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/delete-cron

# Apply cron job
RUN crontab /etc/cron.d/delete-cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# expose python server port
EXPOSE 1235

COPY ./agents-backend/agents/ ./

# create empty report assets dirs
RUN mkdir -p /agents-assets/report-assets
RUN mkdir -p /agents-assets/report-assets/boxplots 
RUN mkdir -p /agents-assets/report-assets/datasets 
RUN mkdir -p /agents-assets/report-assets/heatmaps 
RUN mkdir -p /agents-assets/report-assets/kaplan-meier-plots 
RUN mkdir -p /agents-assets/report-assets/linechart 
RUN mkdir -p /agents-assets/report-assets/linecharts
RUN touch /agent-logs-out

RUN crontab /etc/cron.d/delete-cron

# copy main supervisor conf
COPY ./agents-backend/docker-setup-files/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# copy supervisor startup conf
COPY ./agents-backend/docker-setup-files/start-python-server.conf /etc/supervisor/conf.d/start-python-server.conf

# start startup script
CMD /bin/bash /startup.sh $OPENAI_API_KEY