# builds image for the agents backend
FROM python:3.10

WORKDIR agents-backend

# copy google creds
COPY ./cloud-storage-creds.json /cloud-storage-creds.json

# copy supervisord config
COPY ./agents-backend/docker-setup-files/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# copy rabbitmq installation script
COPY ./agents-backend/docker-setup-files/install_rabbitmq.sh /install_rabbitmq.sh

# run startup script
COPY ./agents-backend/docker-setup-files/startup.sh /startup.sh


# make directory called logs 
RUN mkdir /agents-backend/logs

# install nodejs
RUN apt-get update && apt-get install -y \
    software-properties-common \
    npm

# install npm
RUN npm install npm@latest -g && \
    npm install n -g && \
    n latest


# install rabbitmq
RUN chmod +x /install_rabbitmq.sh
RUN /install_rabbitmq.sh

# RUN rabbitmqctl add_user admin password
# RUN rabbitmqctl set_user_tags admin administrator
# RUN rabbitmqctl set_permissions -p "/" "admin" "^cart-order.*" "^cart-order.*" "^cart-order.*"


# setup supervisord
# need cmake for scikit
RUN apt-get install -y supervisor python3-pip cmake nginx



COPY ./agents-backend/agents/agents ./agents
COPY ./agents-backend/agents/partykit-server ./partykit-server
COPY ./agents-backend/agents/__init__.py ./__init__.py
COPY ./agents-backend/agents/.env.yaml ./.env.yaml
COPY ./agents-backend/agents/connection_manager.py ./connection_manager.py
COPY ./agents-backend/agents/db_utils.py ./db_utils.py
COPY ./agents-backend/agents/doc_endpoints.py ./doc_endpoints.py
COPY ./agents-backend/agents/gcs_consumer.py ./gcs_consumer.py
COPY ./agents-backend/agents/gcs_utils.py ./gcs_utils.py
COPY ./agents-backend/agents/genmab_sample.csv ./genmab_sample.csv
COPY ./agents-backend/agents/main.py ./main.py
COPY ./agents-backend/agents/README.md ./README.md
COPY ./agents-backend/agents/report_data_manager.py ./report_data_manager.py
COPY ./agents-backend/agents/requirements.txt ./requirements.txt
COPY ./agents-backend/agents/send_email.py ./send_email.py
COPY ./agents-backend/agents/slack_utils.py ./slack_utils.py
COPY ./agents-backend/agents/sync-gcs.py ./sync-gcs.py
COPY ./agents-backend/agents/utils.py ./utils.py

# create empty report assets dirs
RUN mkdir -p /agents-backend/report_assets
RUN mkdir -p /agents-backend/report_assets/boxplots 
RUN mkdir -p /agents-backend/report_assets/datasets 
RUN mkdir -p /agents-backend/report_assets/heatmaps 
RUN mkdir -p /agents-backend/report_assets/kaplan-meier-plots 
RUN mkdir -p /agents-backend/report_assets/linechart 
RUN mkdir -p /agents-backend/report_assets/linecharts


# copy nginx config
COPY ./agents-backend/docker-setup-files/nginx.conf /etc/nginx/sites-available/default

COPY ./agents-backend/docker-setup-files/start.conf /etc/supervisor/conf.d/start.conf


# install requirements
RUN pip install -r requirements.txt

# # need node for partykit
# FROM node:latest
# # install partykit
WORKDIR partykit-server
RUN npm install

# expose python server port
EXPOSE 1235
# expose partykit server port
EXPOSE 1999

# remove rabbitmq installation script
RUN rm /install_rabbitmq.sh

# start startup script
CMD ["/bin/bash", "/startup.sh"]