import Meta from "$components/layout/Meta";
import Scaffolding from "$components/layout/Scaffolding";
import { Button, Col, Input, message, Upload, Select } from "antd";
import { useCallback, useEffect, useRef, useState } from "react";
import {
  CloseCircleOutlined,
  InboxOutlined,
  MinusOutlined,
} from "@ant-design/icons";

import CodeMirror, { EditorView } from "@uiw/react-codemirror";
import { sql as codemirrorSql } from "@codemirror/lang-sql";
import { twMerge } from "tailwind-merge";
import setupBaseUrl from "$utils/setupBaseUrl";

const { Dragger } = Upload;

interface ValidationResult {
  /**
   * Whether this query was correctly generated by the model or not.
   */
  correct: string;
  model_sql: string;
}

interface RegressionItem {
  /**
   * This is the array of questions. If it's more than 1 question, all but the last one will be taken as previous questions (and then sent to defog as "previous_context" after generating SQL for each of them) and will be testted as a follow on question.
   */
  questions: string[];
  /**
   * The correct SQL
   */
  sql: string;
  /**
   * Whether we have validated this question or not
   */
  validationResult?: ValidationResult;
}

/**
 * Contains all the regression items so far.
 */
type RegressionItems = RegressionItem[];

export default function TestRegressionPage() {
  const [apiKeyNames, setApiKeyNames] = useState([]);
  const [apiKeyName, setApiKeyName] = useState(null);

  const input = useRef(null);
  const editor = useRef(null);

  const [questions, setQuestions] = useState<RegressionItems>([]);

  const [questionToBeAdded, setQuestionToBeAdded] = useState<RegressionItem>({
    questions: [],
    sql: "",
  });

  const getApiKeyNames = async (token) => {
    const res = await fetch(
      (process.env.NEXT_PUBLIC_AGENTS_ENDPOINT || "") + "/get_api_key_names",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          token: token,
        }),
      }
    );
    if (!res.ok) {
      throw new Error(
        "Failed to get api key names - are you sure your network is working?"
      );
    }
    const data = await res.json();
    setApiKeyNames(data.api_key_names);
  };

  const [token, setToken] = useState(null);

  const [filter, setFilter] = useState(""); // filter for search

  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const apiKeyName = localStorage.getItem("defogDbSelected");
    const token = localStorage.getItem("defogToken");
    getApiKeyNames(token);
    if (apiKeyName) {
      setApiKeyName(apiKeyName);
    } else {
      setApiKeyName(apiKeyNames[0]);
    }
    setToken(token);
  }, []);

  useEffect(() => {
    if (apiKeyName) {
      localStorage.setItem("defogDbSelected", apiKeyName);
    }
  }, [apiKeyName]);

  const getRegressionResults = useCallback(
    async (question = null) => {
      try {
        setLoading(true);
        const res = await fetch(
          setupBaseUrl("http", `readiness/regression_results`),
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              token: token,
              key_name: apiKeyName,
              // we can either test with single question or with all the questions
              questions: question ? [question] : questions,
            }),
          }
        );
        const data = await res.json();
        console.log(data);
      } catch (e) {
        console.log(e);
      } finally {
        setLoading(false);
      }
    },
    [questions, apiKeyName, token]
  );

  return (
    <div className="flex justify-center">
      <Meta />
      <Scaffolding id={"view-feedback"} userType={"admin"}>
        {apiKeyNames.length > 1 ? (
          <div>
            <Col span={24} style={{ paddingBottom: "1em" }}>
              <Select
                style={{ width: "100%" }}
                title="Select API Key"
                onChange={(e) => {
                  setApiKeyName(e);
                }}
                options={apiKeyNames.map((item) => {
                  return { value: item, key: item, label: item };
                })}
                value={apiKeyName}
              />
            </Col>
          </div>
        ) : null}
        <div className="flex flex-col gap-3 mb-4">
          <div className="w-full bg-gray-50 rounded-md border">
            <Dragger
              name={"file"}
              showUploadList={false}
              rootClassName="*:text-left *:border-none *:bg-transparent"
              accept=".json"
              onDrop={(e) => {
                const file = e.dataTransfer.files[0];
                if (file.type !== "application/json") {
                  message.error("Only JSON files accepted");
                  return;
                }

                // read the file as json, and
                // check that the format of this json matches the RegressionItem type
                const reader = new FileReader();

                reader.readAsText(file);

                reader.onload = async (e) => {
                  const result = e.target.result;

                  try {
                    const json = JSON.parse(result);
                    if (json instanceof Array) {
                      if (
                        json.every((item) => {
                          return (
                            item.questions instanceof Array &&
                            item.sql &&
                            typeof item.sql === "string"
                          );
                        })
                      ) {
                        setQuestions(json);
                        message.success("JSON uploaded successfully");
                      } else {
                        message.error(
                          "Invalid JSON format. The JSON should be an array, and each item must have a `questions` property which is an array, and an `sql` property which is a string."
                        );
                      }
                    } else {
                      message.error("Could not upload JSON.");
                    }
                  } catch (e) {
                    message.error("Could not upload JSON.");
                  }
                };
              }}
            >
              <InboxOutlined className="text-4xl"></InboxOutlined>
              <h1 className="font-bold text-sm mb-2">Upload a JSON file</h1>
              <p className="mb-2">Click or drag files to this area to upload</p>
            </Dragger>
          </div>

          <div className="w-full bg-gray-50 rounded-md border">
            <div className="flex flex-row items-center border-b p-4">
              <h1 className="text-sm font-bold">Or add a question manually</h1>
              <div className="grow text-right">
                <Button
                  type={"primary"}
                  onClick={() => {
                    if (
                      questionToBeAdded.questions.length === 0 &&
                      !input.current.input.value
                    ) {
                      message.error("Please add at least one question");
                      return;
                    } else if (!questionToBeAdded.sql) {
                      message.error("Please add the SQL query");
                      return;
                    } else if (
                      questionToBeAdded.questions.length === 0 &&
                      input.current.input.value
                    ) {
                      setQuestions([
                        {
                          questions: [input.current.input.value],
                          sql: questionToBeAdded.sql || "",
                        },
                        ...questions,
                      ]);

                      input.current.input.value = "";
                    } else {
                      setQuestions([questionToBeAdded, ...questions]);
                    }

                    setQuestionToBeAdded({
                      questions: [],
                      sql: "",
                    });

                    input.current.input.value = "";
                  }}
                >
                  Add
                </Button>
              </div>
            </div>
            <div className="py-4">
              <div className="grid grid-cols-10 text-gray-500 relative px-4 gap-3">
                <div className="col-span-4 relative flex flex-col p-4 border rounded-md">
                  {questionToBeAdded.questions.map((question, index) => {
                    return (
                      <div
                        key={index}
                        className={twMerge(
                          "relative group",
                          index === questionToBeAdded.questions.length - 1
                            ? twMerge(
                                "text-lg font-semibold mb-4 text-gray-800",
                                questionToBeAdded.questions.length > 1 && "mb-1"
                              )
                            : "text-sm"
                        )}
                      >
                        <div className="flex flex-row items-center">
                          {question}
                        </div>
                      </div>
                    );
                  })}

                  <div className="flex flex-row items-center group">
                    <div className="flex flex-col items-start gap-2">
                      <span className="text-sm">
                        {questionToBeAdded.questions.length
                          ? "Keep typing to create a follow-on question"
                          : "Type and press Enter to create a question"}
                      </span>
                      <Input
                        size="middle"
                        type="text"
                        placeholder="New question"
                        className="rounded-md border-gray-300 p-1 px-2"
                        ref={input}
                        onPressEnter={(e) => {
                          if (e.currentTarget.value === "") {
                            return;
                          }

                          setQuestionToBeAdded({
                            ...questionToBeAdded,
                            questions: [
                              ...questionToBeAdded.questions,
                              e.currentTarget.value,
                            ],
                          });
                        }}
                      />
                    </div>
                  </div>
                </div>
                <div className="col-span-6 relative flex flex-col gap-2 p-4 border rounded-md">
                  <span className="text-sm">
                    Enter the correct SQL for the final question here
                  </span>
                  <CodeMirror
                    className="border border-gray-300"
                    extensions={[codemirrorSql(), EditorView.lineWrapping]}
                    value={questionToBeAdded.sql}
                    basicSetup={{
                      lineNumbers: false,
                    }}
                    ref={editor}
                    editable={true}
                    onChange={(value) => {
                      setQuestionToBeAdded({
                        ...questionToBeAdded,
                        sql: value,
                      });
                    }}
                  />
                </div>
              </div>
            </div>
          </div>

          <div className="h-10 w-full flex items-center">
            <div className="h-0.5 w-full bg-gray-300"></div>
          </div>

          <div className="bg-gray-50 rounded-md border">
            <div className="flex flex-row items-center mb-4 border-b p-4">
              <h1 className="text-sm font-bold">Added questions</h1>
              <div className="grow text-right space-x-2">
                <Button
                  onClick={() => {
                    const element = document.createElement("a");
                    const file = new Blob(
                      [JSON.stringify(questions, null, 2)],
                      {
                        type: "application/json",
                      }
                    );
                    element.href = URL.createObjectURL(file);
                    element.download = "regression.json";
                    document.body.appendChild(element); // Required for this to work in FireFox
                    element.click();
                  }}
                >
                  Download JSON
                </Button>
                <Button
                  type="primary"
                  loading={loading}
                  disabled={!questions.length}
                  onClick={async () => {
                    await getRegressionResults();
                  }}
                >
                  Validate All
                </Button>
              </div>
            </div>
            {questions.length ? (
              <div className="px-4 my-4">
                <Input
                  className="rounded-md border-gray-300 w-40 p-1 px-2"
                  size="small"
                  type="text"
                  placeholder="Filter questions"
                  value={filter}
                  onChange={(e) => setFilter(e.target.value)}
                />
              </div>
            ) : (
              <div className="p-4 text-gray-500">
                Please add questions above or upload a JSON file.
              </div>
            )}
            <div className="flex flex-col">
              {questions
                .filter((item) => {
                  return item.questions
                    .map((question) => {
                      return question
                        .toLowerCase()
                        .includes(filter.toLowerCase());
                    })
                    .some((item) => item);
                })
                .map((item, idx) => {
                  return (
                    <div
                      key={idx}
                      className="grid grid-cols-12 text-gray-500 relative even:bg-gray-100"
                    >
                      <div className="col-span-4 relative flex flex-col px-6 py-4 border-r">
                        {item.questions.map((question, j) => {
                          return (
                            <div
                              key={j}
                              className={twMerge(
                                "flex flex-row items-center",
                                j === item.questions.length - 1
                                  ? "text-lg font-semibold mb-1 text-gray-800"
                                  : "text-sm"
                              )}
                            >
                              <div>{question}</div>
                            </div>
                          );
                        })}
                      </div>
                      <div className="col-span-6 border-r p-4">
                        <CodeMirror
                          className="border border-gray-300"
                          extensions={[
                            codemirrorSql(),
                            EditorView.lineWrapping,
                          ]}
                          value={item.sql}
                          basicSetup={{
                            lineNumbers: false,
                          }}
                          ref={editor}
                          editable={false}
                        />
                      </div>
                      <div className="col-span-2 p-4">
                        {item.validationResult ? (
                          <>
                            Validated: {JSON.stringify(item.validationResult)}
                          </>
                        ) : (
                          <Button
                            loading={loading}
                            disabled={loading}
                            onClick={async () => {
                              await getRegressionResults(item);
                            }}
                          >
                            Validate
                          </Button>
                        )}
                      </div>
                    </div>
                  );
                })}
            </div>
          </div>
        </div>
      </Scaffolding>
    </div>
  );
}
