-- holds the schema for all the required tables for the postgres db
-- all Owner: cloudsqlexternalsync have been changed to Owner: postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4
-- Dumped by pg_dump version 16.1 (Ubuntu 16.1-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: defog_docs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defog_docs (
    doc_id text NOT NULL,
    doc_md text,
    doc_blocks jsonb,
    editor_defog_blocks jsonb,
    api_key text NOT NULL,
    "timestamp" text,
    username text,
    doc_xml text,
    doc_uint8 jsonb,
    doc_title text,
    archived boolean default false
);


ALTER TABLE public.defog_docs OWNER TO postgres;

--
-- Name: COLUMN defog_docs.doc_blocks; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.defog_docs.doc_blocks IS 'This is the internal blocknote/tiptap representation of the document. This INCLUDES the defog_blocks too like analysis, etc.';


--
-- Name: COLUMN defog_docs.editor_defog_blocks; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.defog_docs.editor_defog_blocks IS 'This is just a filtered version of the editor_blocks. Contains just the blocks with special analysis, etc that are generated by the model. These are included in the editor_blocks column.';


--
-- Name: defog_recently_viewed_docs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defog_recently_viewed_docs (
    api_key text NOT NULL,
    username text NOT NULL,
    recent_docs jsonb
);


ALTER TABLE public.defog_recently_viewed_docs OWNER TO postgres;

--
-- Name: defog_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defog_reports (
    api_key text NOT NULL,
    email text,
    "timestamp" text,
    report_uuid text,
    approaches json,
    report_markdown text,
    clarify jsonb,
    understand jsonb,
    gen_approaches jsonb,
    user_question text,
    gen_report jsonb,
    report_id text NOT NULL,
    gen_steps jsonb,
    follow_up_analyses jsonb,
    parent_analyses jsonb
);


ALTER TABLE public.defog_reports OWNER TO postgres;

--
-- Name: defog_table_charts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defog_table_charts (
    data_csv jsonb,
    query text,
    chart_images jsonb,
    sql text,
    code text,
    table_id text NOT NULL,
    tool jsonb,
    edited boolean,
    error text,
    reactive_vars jsonb
);


ALTER TABLE public.defog_table_charts OWNER TO postgres;

--
-- Name: defog_tool_runs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defog_tool_runs (
    tool_run_id text NOT NULL,
    step jsonb,
    outputs jsonb,
    tool_name text,
    tool_run_details jsonb,
    error_message text,
    edited boolean,
    analysis_id text
);


ALTER TABLE public.defog_tool_runs OWNER TO postgres;

--
-- Name: defog_toolboxes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defog_toolboxes (
    api_key text NOT NULL,
    username text NOT NULL,
    toolboxes jsonb
);


ALTER TABLE public.defog_toolboxes OWNER TO postgres;

--
-- Name: defog_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defog_users (
    username text NOT NULL,
    hashed_password text,
    token text NOT NULL,
    user_type text NOT NULL,
    csv_tables text,
    is_premium boolean,
    created_at timestamp without time zone,
    is_verified boolean
);


ALTER TABLE public.defog_users OWNER TO postgres;

--
-- Name: defog_docs defog_docs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defog_docs
    ADD CONSTRAINT defog_docs_pkey PRIMARY KEY (api_key, doc_id);


--
-- Name: defog_recently_viewed_docs defog_recently_viewed_docs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defog_recently_viewed_docs
    ADD CONSTRAINT defog_recently_viewed_docs_pkey PRIMARY KEY (api_key, username);


--
-- Name: defog_reports defog_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defog_reports
    ADD CONSTRAINT defog_reports_pkey PRIMARY KEY (report_id, api_key);


--
-- Name: defog_table_charts defog_table_charts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defog_table_charts
    ADD CONSTRAINT defog_table_charts_pkey PRIMARY KEY (table_id);


--
-- Name: defog_toolboxes defog_toolboxes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defog_toolboxes
    ADD CONSTRAINT defog_toolboxes_pkey PRIMARY KEY (username, api_key);


--
-- Name: defog_users defog_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defog_users
    ADD CONSTRAINT defog_users_pkey PRIMARY KEY (username);


--
-- Name: defog_tool_runs tool_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defog_tool_runs
    ADD CONSTRAINT tool_runs_pkey PRIMARY KEY (tool_run_id);


--
-- PostgreSQL database dump complete
--

